# Generated by Django 3.1.5 on 2021-01-12 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('Name', models.CharField(max_length=150)),
                ('Image', models.ImageField(upload_to='picture')),
                ('Description', models.TextField()),
                ('Content', models.TextField()),
            ],
        ),
    ]
